language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user:
    secure: VXh6wmCw8XZ4bMWXgQ504+g8uab8bIvy3QwfpdnUrH+hgLYIwo7nOVTaiAbqGTCHksEjjgj0ST5Y+EOyZkrBCBOl8igEXh6KMygU8ObZYz9NJ3tj3jTflrCTsoghSzoP3xeHoLWhX4w5sQjokWgvaCetHSL2OlwGCXXXdXNIe8dY0tUgJliQMa5Xy1mrHNefwQfG6yYGPrBqA0Vgi3XUSysuPF4MCSMUP7xpWPRxR4ZE7b7uc6ofMBBjXnfVHuQ/au6J4v8BqdAee+dvIXX1+P2hLCOsrZYSg0zoVJ5FssiDw8BWJhRXruOulUhUygAWVEYKLcTnCG9EH5vIkTrzwdZkV1qQoKtCcU20LzuBOhJxZDKTpJZ5Ext7db6r4DzZQM8XOEJ55O2MwLG2a9CoBQ8SDzpNBCSt9sGdYM8yP2HS+QAg/3Y9YujoXAZLk97OOXBX/PmXXENl5+69UCZxav7EuUQoidQ/MJGnT5na3bTa4pkcGU0eFrqLyhns14FLaQNx062HtTDgJSKbxheZR8+BRUyunhYlx+2n6AhV0/Spe7vyzECG30zez0O5FxPU4DmHxh+76cRXRTNm8Ktay02/y3w0ujExt1ZXEHzE6aPv+JZM30AtX0/bIVJKzIbiVHARUCT7l1ym2IYj/IehxfSPhMrEt1bSGQJbgyuEFw4=
  password:
    secure: BL85VyjQrpiWwTS7bNqcdnlwyt0KjZ4JuRkFbmS5DO8EX1+C1nIEtKBqqNhBoNm5xZQJRplnglSvu26AweTitPq+N7KHSXD5wF7fBMiD6XIY3OduiISLtGTyUEA/vB+GRCisQVWHzMIh88Nwp8Zony9YZA6/diUrtuflsam6MlPzpKBX1icNg+ChfZABqGYvJyghpx0RW5pGpgHuU3HdR5aaLmPCk6ziTqsJI/z5IXAeefZ/m6FXXLU36S2lXEvgfAeH9ob10ly8q+RpRPff30G+tOOMBSABdMzyyv/XNJsWPA9F3UETkq/pwV2/qipU+9sWCDILMLvZkIrAMkYBr3fiRBRl2vzukUjw9Yo2pQSZH+OxMnRpQLqWh1MlCTfAz99fsc6xzt1EuENqvA9uK7eiNmWfaAdlmNzOzZotQaOHGbOcY5N3cm3JK1G+Gg6RRUl2iXHaEzB0s9aWM6pZW2z+nBoXulpILMEkrNeaRsCrdrYfMDM1UTF+QY4M+sSMkMZy8qocygtToU/DEKJI8I0ebLarAYFrans6JtbzNNl+yPM0PcH5it4uVk3HVXsgOraxys1+HTreGyyX0PnpBvK7IgG8u76j9zm9fEnfW3KzynOAP0tAcIApuXZlEOwfqXEtCIGklQctZK/sqZcZUyek9Xvmo2vzzXeBrea1TZ8=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
