language: python
python:
- '2.7'
script:
- touch foo
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cvium
  password:
    secure: NvXU9mWRDovhsJwpNG/zvpy5KhlBJpeRfBn1Ejvs73OuJ9Aw05TS3k90RAOc7A60H/dJf38L9JZ5QqZTMCjQynkALHMSJPOlv/tEBlvhAuAKq+ZsApKtoiNphorSbVWG0zKZD9Ar7HUOBCAWAeZxGD/17HBbMQhuINs+oeZq/JPy5p/LWQRW6LNqCOLHTKsP4wSxkgimNVfiYQvjTKbQssOqDdehBLm1DQ6VR/mYu56wvNYth1jaiA47Hoj4MTDtoaeyAqZROjBT+mNPK5Kn0JxOFlMYdJffnqhnew+FfDAYHtj5xlBJfTcqCsbm62pSt1vTb9fzkLW4wZW4rjAcAEpK+Hl8uzTP2Sjk2pjRdRvEdCTGxLs+1QICE1LcBX+x7cIrxn6U+QiwWWYiGqSCvGydNP88JxnhMRt4Ea/IhAPvtJ4+rIL7fDaxbc4SVFGSfDUH3o6X5EuToJysfQZ1yJKiSr8+nV0yX+FsO1Z5z6/gxIl6GAWsmG69SfPkxLijCfA8S1BaO9s0Sb0u2Ok6SS+unuVunt8xpPxi5c9kicc9212O6QCKzFAdgK8hvMDaq6pYFcdypQp5I/YL9AYPHLIpmbp54fe61hKafxVaV9r5uQmnI7Dym0Bx+OLBs7uGgUKM3T61ZioyFc4XWGH6iLcGfizFdubjBws3iBFiVw4=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
